import React, { useState, useCallback, useEffect, memo } from 'react'
import Header from '../customComponents/Header'
import MobileMenu from '../customComponents/MobileMenu'
import './gamerules.css'

const RULE_TILES = [
  { id: 'cricket', title: 'Cricket Betting Rules', icon: 'ri-cricket-ball-line' },
  { id: 'football', title: 'Football Betting Rules', icon: 'ri-football-line' },
  { id: 'tennis', title: 'Tennis & Other Sports', icon: 'ri-trophy-line' },
  { id: 'casino', title: 'Casino & Games Rules', icon: 'ri-poker-spades-fill' },
  { id: 'general', title: 'General Rules', icon: 'ri-file-list-3-line' },
  { id: 'settlement', title: 'Settlement, Void & Fair Play', icon: 'ri-shield-check-line' },
]

function IconLi({ icon, children }) {
  return (
    <li>
      <i className={`${icon} game_rules_faq_li_icon`} aria-hidden />
      <span>{children}</span>
    </li>
  )
}

function RuleModalBody({ ruleId }) {
  switch (ruleId) {
    case 'cricket':
      return (
        <ul className="game_rules_card_list_with_icon">
          <IconLi icon="ri-trophy-line"><strong>Match winner:</strong> Bets are settled on the official result published by the governing body. If D/L or VJD is applied, settlement follows that official outcome.</IconLi>
          <IconLi icon="ri-timer-line"><strong>Minimum overs:</strong> For limited-overs formats, markets stand only if minimum overs criteria are met under the tournament rules. If criteria are not met, unsettled markets are void and stake is returned.</IconLi>
          <IconLi icon="ri-scales-3-line"><strong>Innings and session markets:</strong> Session, fancy, and innings runs are settled on the official score at completion or official stoppage of that segment.</IconLi>
          <IconLi icon="ri-calendar-close-line"><strong>Postponed or abandoned matches:</strong> If a match is not completed as per official schedule and reserve-day policy, undecided markets are void. Already decided markets remain settled.</IconLi>
          <IconLi icon="ri-user-star-line"><strong>Player markets:</strong> Player performance markets are settled using official stats. If the player does not participate in the relevant market condition, bets may be void as per market type.</IconLi>
        </ul>
      )
    case 'football':
      return (
        <ul className="game_rules_card_list_with_icon">
          <IconLi icon="ri-football-line"><strong>Normal-time settlement:</strong> 1X2, handicap, and total goals are settled on 90 minutes plus injury time only, unless market states extra time or penalties included.</IconLi>
          <IconLi icon="ri-calendar-line"><strong>Postponement window:</strong> If a fixture is not played within the stated market window (commonly 48 hours unless specified), unsettled bets are void.</IconLi>
          <IconLi icon="ri-stop-circle-line"><strong>Abandonment:</strong> On abandoned matches, markets already decided are settled and all remaining undecided markets are void.</IconLi>
          <IconLi icon="ri-focus-3-line"><strong>Goals and own goals:</strong> Total goals and score-based markets follow official match reports and accredited stats providers.</IconLi>
          <IconLi icon="ri-flag-line"><strong>Cards and corners:</strong> Settled as per official statistics for normal time play. Events awarded but not taken generally do not count.</IconLi>
        </ul>
      )
    case 'tennis':
      return (
        <ul className="game_rules_card_list_with_icon">
          <IconLi icon="ri-trophy-line"><strong>Tennis match winner:</strong> Settled on the player who officially progresses or is declared winner by tournament authority.</IconLi>
          <IconLi icon="ri-skip-forward-line"><strong>Retirement and walkover:</strong> If play has not started and official walkover is declared, bets are void. If retirement happens after start, settlement depends on market type and governing rules.</IconLi>
          <IconLi icon="ri-global-line"><strong>Other sports:</strong> All markets are settled from official governing-body results, score feeds, and rule books.</IconLi>
        </ul>
      )
    case 'casino':
      return (
        <ul className="game_rules_card_list_with_icon">
          <IconLi icon="ri-poker-spades-fill"><strong>Teen Patti and card games:</strong> Game outcomes follow the in-table rules shown by provider. Hand ranking and tie logic are taken from the live or RNG game engine.</IconLi>
          <IconLi icon="ri-record-circle-line"><strong>Roulette:</strong> Settlement is based on the final wheel pocket result shown by the provider for that round.</IconLi>
          <IconLi icon="ri-loop-right-line"><strong>Slots and RNG games:</strong> Results are generated by certified RNG systems. Completed rounds are final unless provider reports a technical malfunction.</IconLi>
          <IconLi icon="ri-vidicon-line"><strong>Live casino:</strong> Dealer calls and provider game logs are treated as final reference for settlement.</IconLi>
          <IconLi icon="ri-gift-line"><strong>Bonuses and promotions:</strong> Offer validity, wagering requirement, game contribution, and expiry are governed by promo terms shown in your account.</IconLi>
        </ul>
      )
    case 'general':
      return (
        <ul className="game_rules_card_list_with_icon">
          <IconLi icon="ri-user-follow-line"><strong>Eligibility:</strong> You must be 18+ and legally allowed to use betting and gaming services in your jurisdiction.</IconLi>
          <IconLi icon="ri-account-box-line"><strong>Single account policy:</strong> One user may hold one active account only. Incorrect KYC details, duplicate accounts, or account sharing may lead to restrictions.</IconLi>
          <IconLi icon="ri-line-chart-line"><strong>Odds and limits:</strong> Accepted odds at placement time are final. We may limit stakes, cancel obvious-price-error bets, or apply payout caps as per terms.</IconLi>
          <IconLi icon="ri-hand-heart-line"><strong>Responsible gaming:</strong> Use available controls like deposit limits, session controls, and self-exclusion whenever needed.</IconLi>
          <IconLi icon="ri-file-paper-2-line"><strong>Terms acceptance:</strong> By betting or playing games on this platform, you agree to the latest Game Rules and Terms and Conditions.</IconLi>
        </ul>
      )
    case 'settlement':
      return (
        <ul className="game_rules_card_list_with_icon">
          <IconLi icon="ri-checkbox-circle-line"><strong>Official source:</strong> All market settlements are based on official results, provider data, and recognized sports statistics feeds.</IconLi>
          <IconLi icon="ri-equalizer-line"><strong>Dead heat:</strong> If multiple selections tie for a paid position, dead-heat calculation is applied proportionately to stake and odds.</IconLi>
          <IconLi icon="ri-forbid-line"><strong>Void markets:</strong> Cancelled events, technical errors, duplicated markets, or rule breaches can lead to void settlement with stake refund.</IconLi>
          <IconLi icon="ri-shield-star-line"><strong>Disputes and fair play:</strong> For settlement queries, raise a Help / Support ticket with your bet ID and event details. Fraud, bot use, collusion, or abuse may result in account action.</IconLi>
        </ul>
      )
    default:
      return null
  }
}

const GameRules = memo(function GameRules() {
  const [openModalId, setOpenModalId] = useState(null)

  const openModal = useCallback((id) => setOpenModalId(id), [])
  const closeModal = useCallback(() => setOpenModalId(null), [])

  useEffect(() => {
    if (!openModalId) return undefined
    const onKey = (e) => {
      if (e.key === 'Escape') closeModal()
    }
    window.addEventListener('keydown', onKey)
    const prevOverflow = document.body.style.overflow
    document.body.style.overflow = 'hidden'
    return () => {
      window.removeEventListener('keydown', onKey)
      document.body.style.overflow = prevOverflow
    }
  }, [openModalId, closeModal])

  const activeTile = RULE_TILES.find((t) => t.id === openModalId)

  return (
    <>
      <Header />
      <div className="game_rules_root">
        <div className="dashboard_page game_rules_section">
          <div className="container-fluid game_rules_container">
            <div className="promotions_top_hd">
              <div className="promotions_top_hd_row">
                <div className="promotions_top_hd_icon" aria-hidden>
                  <i className="ri-book-2-line" />
                </div>
                <div className="promotions_top_hd_text">
                  <h1>Game Rules</h1>
                  <p>Read these rules before placing bets or playing games. All activity on this platform is settled under these rules and the latest Terms &amp; Conditions.</p>
                </div>
              </div>
            </div>

            <div className="game_rules_grid">
              {RULE_TILES.map((tile) => (
                <button
                  key={tile.id}
                  type="button"
                  className="game_rules_tile"
                  onClick={() => openModal(tile.id)}
                >
                  <div className="game_rules_tile_icon" aria-hidden>
                    <i className={tile.icon} />
                  </div>
                  <div className="game_rules_tile_body">
                    <h2 className="game_rules_tile_title">{tile.title}</h2>
                    <span className="game_rules_tile_action">
                      Read rules
                      <i className="ri-external-link-line" aria-hidden />
                    </span>
                  </div>
                </button>
              ))}
            </div>
          </div>
        </div>

        {openModalId && activeTile ? (
        <div
          className="game_rules_modal_backdrop"
          onClick={closeModal}
          role="presentation"
        >
          <div
            className="game_rules_modal_dialog"
            role="dialog"
            aria-modal="true"
            aria-labelledby="game-rules-modal-title"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="game_rules_modal_head">
              <div className="game_rules_modal_head_left">
                <div className="game_rules_modal_head_icon" aria-hidden>
                  <i className={activeTile.icon} />
                </div>
                <h2 id="game-rules-modal-title" className="game_rules_modal_head_title">
                  {activeTile.title}
                </h2>
              </div>
              <button type="button" className="game_rules_modal_close" onClick={closeModal} aria-label="Close">
                <i className="ri-close-line" aria-hidden />
              </button>
            </div>
            <div className="game_rules_modal_body">
              <div className="game_rules_modal_inner">
                <RuleModalBody ruleId={openModalId} />
              </div>
            </div>
          </div>
        </div>
        ) : null}
      </div>

      <MobileMenu />
    </>
  )
})

export default GameRules
